quotes = [
    "`The best way to predict the future is to create it. - Abraham Lincoln`",
    "`Believe you can and you're halfway there. - Theodore Roosevelt`",
    "`Stay positive and happy. Work hard and don't give up hope. Be open to criticism and keep learning. Surround yourself with happy, warm and genuine people. - Tena Desae`",
    "`In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact. - Les Brown`",
    "`Positive thinking will let you do everything better than negative thinking will. - Zig Ziglar`",
    "`The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt`",
    "`You are never too old to set another goal or to dream a new dream. - C.S. Lewis`",
    "`The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey`",
    "`With the new day comes new strength and new thoughts. - Eleanor Roosevelt`",
    "`Positive anything is better than negative nothing. - Elbert Hubbard`",
    "`Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar`",
    "`Winning doesn't always mean being first. Winning means you're doing better than you've done before. - Bonnie Blair`",
    "`It always seems impossible until it is done. - Nelson Mandela`",
    "`You don’t have to be perfect to be amazing.`",
    "`Start where you are. Use what you have. Do what you can. - Arthur Ashe`",
    "`Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller`",
    "`You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne`",
    "`The way to get started is to quit talking and begin doing. - Walt Disney`",
    "`Happiness is not something ready made. It comes from your own actions. - Dalai Lama`",
    "`Keep your face always toward the sunshine - and shadows will fall behind you. - Walt Whitman`"
]

riddles = [
    "`Here is a riddle:`\n I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?\n `Answer:` ||an echo||",
    "`Here is a riddle:`\n The more of this there is, the less you see. What is it?\n `Answer:` ||darkness||",
    "`Here is a riddle:`\n What comes once in a minute, twice in a moment, but never in a thousand years?\n `Answer:` ||the letter 'm'||",
    "`Here is a riddle:`\n What has a head, a tail, is brown, and has no legs?\n `Answer:` ||a penny||",
    "`Here is a riddle:`\n I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?\n `Answer:` ||a map||",
    "`Here is a riddle:`\n What has keys that open no locks, space but no room, and you can enter but not go in?\n `Answer:` ||a keyboard||",
    "`Here is a riddle:`\n The more you take, the more you leave behind. What am I?\n `Answer:` ||footsteps||",
    "`Here is a riddle:`\n What has one eye but can't see?\n `Answer:` ||a needle||",
    "`Here is a riddle:`\n What runs but never walks, has a bed but never sleeps?\n `Answer:` ||a river||",
    "`Here is a riddle:`\n What has a neck but no head?\n `Answer:` ||a bottle||",
    "`Here is a riddle:`\n I am taken from a mine, and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?\n `Answer:` ||pencil lead||",
    "`Here is a riddle:`\n What is full of holes but still holds water?\n `Answer:` ||a sponge||",
    "`Here is a riddle:`\n What has keys but can't open doors?\n `Answer:` ||a piano||",
    "`Here is a riddle:`\n What has a heart that doesn't beat?\n `Answer:` ||an artichoke||",
    "`Here is a riddle:`\n What is light as a feather, yet the strongest person can't hold it for much longer than a minute?\n `Answer:` ||your breath||",
    "`Here is a riddle:`\n What has a face and two hands, but no arms or legs?\n `Answer:` ||a clock||",
    "`Here is a riddle:`\n I'm tall when I'm young, and I'm short when I'm old. What am I?\n `Answer:` ||a candle||",
    "`Here is a riddle:`\n What has keys but can't open locks, and space but no room?\n `Answer:` ||a computer keyboard||",
    "`Here is a riddle:`\n What has a head, a tail, but no body?\n `Answer:` ||a coin||",
    "`Here is a riddle:`\n The more you take, the more you leave behind. What am I?\n `Answer:` ||footsteps||",
    "`Here is a riddle:`\n What belongs to you but is used more by others?\n `Answer:` ||your name||",
    "`Here is a riddle:`\n What has one eye but can't see?\n `Answer:` ||a needle||",
    "`Here is a riddle:`\n What has cities, but no houses; forests, but no trees; and rivers, but no water?\n `Answer:` ||a map||",
    "`Here is a riddle:`\n What has keys that open no locks, space but no room, and you can enter but not go in?\n `Answer:` ||a keyboard||",
]


